Disable long jobs

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -18,125 +18,125 @@ jobs:
           go-version: 1.19.10
         id: go
 
-      - name: Setup Go binary path
-        shell: bash
-        run: |
-          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
-          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
+      # - name: Setup Go binary path
+      #   shell: bash
+      #   run: |
+      #     echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
+      #     echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
 
-      - name: Install docker
-        shell: bash
-        run: |
-          arch=$(dpkg --print-architecture)
+      # - name: Install docker
+      #   shell: bash
+      #   run: |
+      #     arch=$(dpkg --print-architecture)
 
-          # Workarounds for error "Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease"
-          # TODO: remove it after the issue fixed in git-lfs.
-          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
-          sudo apt-get update
+      #     # Workarounds for error "Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease"
+      #     # TODO: remove it after the issue fixed in git-lfs.
+      #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
+      #     sudo apt-get update
 
-          # Install prereqs
-          sudo apt-get install -y \
-            conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod \
-            libseccomp2
+      #     # Install prereqs
+      #     sudo apt-get install -y \
+      #       conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod \
+      #       libseccomp2
 
-          # Install docker.
-          sudo apt-get install -y \
-            apt-transport-https \
-            ca-certificates \
-            curl socat \
-            gnupg-agent \
-            software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          sudo add-apt-repository \
-          "deb [arch=$arch] https://download.docker.com/linux/ubuntu \
-           $(lsb_release -cs) \
-           stable"
-          sudo apt-get update
-          sudo apt-cache madison docker-ce
-          sudo apt-get install docker-ce docker-ce-cli containerd.io
+      #     # Install docker.
+      #     sudo apt-get install -y \
+      #       apt-transport-https \
+      #       ca-certificates \
+      #       curl socat \
+      #       gnupg-agent \
+      #       software-properties-common
+      #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+      #     sudo add-apt-repository \
+      #     "deb [arch=$arch] https://download.docker.com/linux/ubuntu \
+      #      $(lsb_release -cs) \
+      #      stable"
+      #     sudo apt-get update
+      #     sudo apt-cache madison docker-ce
+      #     sudo apt-get install docker-ce docker-ce-cli containerd.io
 
-          # Restart docker daemon.
-          sudo service docker restart
+      #     # Restart docker daemon.
+      #     sudo service docker restart
 
-      - name: Checkout cri-dockerd
-        uses: actions/checkout@v2
-        with:
-          repository: ${{ github.repository }}
-          path: src/github.com/Mirantis/cri-dockerd
+      # - name: Checkout cri-dockerd
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: ${{ github.repository }}
+      #     path: src/github.com/Mirantis/cri-dockerd
 
-      - name: Build cri-dockerd
-        working-directory: src/github.com/Mirantis/cri-dockerd
-        run: |
-          go build
-          sudo mv ./cri-dockerd /usr/local/bin
+      # - name: Build cri-dockerd
+      #   working-directory: src/github.com/Mirantis/cri-dockerd
+      #   run: |
+      #     go build
+      #     sudo mv ./cri-dockerd /usr/local/bin
 
-      - name: Start cri-dockerd
-        shell: bash
-        run: |
-          set -x
-          export LANG=C
-          export LC_ALL=C
+      # - name: Start cri-dockerd
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     export LANG=C
+      #     export LC_ALL=C
 
-          # Install nsenter
-          docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
+      #     # Install nsenter
+      #     docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
 
-          # Start cri-dockerd first
-          logs_dir="${{ github.workspace }}/logs"
-          mkdir -p $logs_dir
-          sudo /usr/local/bin/cri-dockerd --log-level warn --network-plugin="" >$logs_dir/cri-dockerd.log 2>&1 &
+      #     # Start cri-dockerd first
+      #     logs_dir="${{ github.workspace }}/logs"
+      #     mkdir -p $logs_dir
+      #     sudo /usr/local/bin/cri-dockerd --log-level warn --network-plugin="" >$logs_dir/cri-dockerd.log 2>&1 &
 
-          # Wait a while for cri-dockerd starting.
-          sleep 10
+      #     # Wait a while for cri-dockerd starting.
+      #     sleep 10
 
-      - name: Check out kubernetes
-        uses: actions/checkout@v2
-        with:
-          repository: kubernetes/kubernetes
-          path: src/k8s.io/kubernetes
-          ref: 84c8abfb8bf900ce36f7ebfbc52794bad972d8cc
+      # - name: Check out kubernetes
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: kubernetes/kubernetes
+      #     path: src/k8s.io/kubernetes
+      #     ref: 84c8abfb8bf900ce36f7ebfbc52794bad972d8cc
 
-      - name: Checkout test-infra for kubetest
-        uses: actions/checkout@v2
-        with:
-          repository: kubernetes/test-infra
-          path: src/k8s.io/test-infra
+      # - name: Checkout test-infra for kubetest
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: kubernetes/test-infra
+      #     path: src/k8s.io/test-infra
 
-      - name: Build kubetest
-        working-directory: src/k8s.io/test-infra
-        shell: bash
-        run: |
-          set -x
-          go install k8s.io/test-infra/kubetest
-          sudo mv $GOPATH/bin/kubetest /usr/local/bin
+      # - name: Build kubetest
+      #   working-directory: src/k8s.io/test-infra
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     go install k8s.io/test-infra/kubetest
+      #     sudo mv $GOPATH/bin/kubetest /usr/local/bin
 
-      - name: Start up a cluster
-        working-directory: src/k8s.io/kubernetes
-        shell: bash
-        run: |
-          set -x
-          make all WHAT="cmd/kubectl test/e2e/e2e.test vendor/github.com/onsi/ginkgo/ginkgo"
-          hack/install-etcd.sh
-          export PATH="$(pwd)/third_party/etcd:${PATH}"
-          mkdir -p ${{ github.workspace }}/logs
+      # - name: Start up a cluster
+      #   working-directory: src/k8s.io/kubernetes
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     make all WHAT="cmd/kubectl test/e2e/e2e.test vendor/github.com/onsi/ginkgo/ginkgo"
+      #     hack/install-etcd.sh
+      #     export PATH="$(pwd)/third_party/etcd:${PATH}"
+      #     mkdir -p ${{ github.workspace }}/logs
 
-          IP=$(ip addr show dev docker0 | grep -w inet | awk '{print $2}' | cut -f1 -d/)
-          sudo env PATH=$PATH \
-            GOPATH=$GOPATH \
-            ENABLE_DAEMON=true \
-            LOG_DIR=${{ github.workspace }}/logs \
-            ALLOW_PRIVILEGED=true \
-            API_HOST_IP=$IP \
-            HOSTNAME_OVERRIDE=$IP \
-            KUBELET_HOST=$IP \
-            CONTAINER_RUNTIME=remote \
-            CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/cri-dockerd.sock" \
-            hack/local-up-cluster.sh 2>&1 | tee ${{ github.workspace }}/logs/local-up-cluster.log
+      #     IP=$(ip addr show dev docker0 | grep -w inet | awk '{print $2}' | cut -f1 -d/)
+      #     sudo env PATH=$PATH \
+      #       GOPATH=$GOPATH \
+      #       ENABLE_DAEMON=true \
+      #       LOG_DIR=${{ github.workspace }}/logs \
+      #       ALLOW_PRIVILEGED=true \
+      #       API_HOST_IP=$IP \
+      #       HOSTNAME_OVERRIDE=$IP \
+      #       KUBELET_HOST=$IP \
+      #       CONTAINER_RUNTIME=remote \
+      #       CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/cri-dockerd.sock" \
+      #       hack/local-up-cluster.sh 2>&1 | tee ${{ github.workspace }}/logs/local-up-cluster.log
 
-      - name: Cleanup processes and containers
-        if: always()
-        shell: bash
-        run: |
-          (docker rm -f $(docker ps -a -q)) || true
-          (docker rmi -f $(docker images -q -a)) || true
-          (docker system prune --all --volumes -f) || true
-          (ps -ef | grep -i -e kube- -e etcd -e dockerd | grep -v grep | awk '{print $2}' | xargs sudo kill -9) || true
+      # - name: Cleanup processes and containers
+      #   if: always()
+      #   shell: bash
+      #   run: |
+      #     (docker rm -f $(docker ps -a -q)) || true
+      #     (docker rmi -f $(docker images -q -a)) || true
+      #     (docker system prune --all --volumes -f) || true
+      #     (ps -ef | grep -i -e kube- -e etcd -e dockerd | grep -v grep | awk '{print $2}' | xargs sudo kill -9) || true
diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -19,128 +19,128 @@ jobs:
           go-version: 1.19.10
         id: go
 
-      - name: Setup environment
-        shell: bash
-        run: |
-          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
-          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
-          sudo sysctl net.ipv6.conf.all.disable_ipv6=0
+      # - name: Setup environment
+      #   shell: bash
+      #   run: |
+      #     echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
+      #     echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
+      #     sudo sysctl net.ipv6.conf.all.disable_ipv6=0
 
-      - name: Install docker
-        shell: bash
-        run: |
-          arch=$(dpkg --print-architecture)
+      # - name: Install docker
+      #   shell: bash
+      #   run: |
+      #     arch=$(dpkg --print-architecture)
 
-          # Workarounds for error "Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease"
-          # TODO: remove it after the issue fixed in git-lfs.
-          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
-          sudo apt-get update
+      #     # Workarounds for error "Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease"
+      #     # TODO: remove it after the issue fixed in git-lfs.
+      #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
+      #     sudo apt-get update
 
-          # Install prereqs
-          sudo apt-get install -y \
-            conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod \
-            libseccomp2
+      #     # Install prereqs
+      #     sudo apt-get install -y \
+      #       conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod \
+      #       libseccomp2
 
-          # Install docker.
-          sudo apt-get install -y \
-            apt-transport-https \
-            ca-certificates \
-            curl socat \
-            gnupg-agent \
-            software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          sudo add-apt-repository \
-          "deb [arch=$arch] https://download.docker.com/linux/ubuntu \
-           $(lsb_release -cs) \
-           stable"
-          sudo apt-get update
-          sudo apt-cache madison docker-ce
-          sudo apt-get install docker-ce docker-ce-cli containerd.io
+      #     # Install docker.
+      #     sudo apt-get install -y \
+      #       apt-transport-https \
+      #       ca-certificates \
+      #       curl socat \
+      #       gnupg-agent \
+      #       software-properties-common
+      #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+      #     sudo add-apt-repository \
+      #     "deb [arch=$arch] https://download.docker.com/linux/ubuntu \
+      #      $(lsb_release -cs) \
+      #      stable"
+      #     sudo apt-get update
+      #     sudo apt-cache madison docker-ce
+      #     sudo apt-get install docker-ce docker-ce-cli containerd.io
 
-          # Restart docker daemon.
-          sudo service docker restart
+      #     # Restart docker daemon.
+      #     sudo service docker restart
 
-      - name: Install ginkgo
-        run: |
-          go install github.com/onsi/ginkgo/v2/ginkgo@latest
-          ginkgo version
-          sudo cp $(command -v ginkgo) /usr/local/bin
+      # - name: Install ginkgo
+      #   run: |
+      #     go install github.com/onsi/ginkgo/v2/ginkgo@latest
+      #     ginkgo version
+      #     sudo cp $(command -v ginkgo) /usr/local/bin
 
-      - name: Check out cri-tools
-        uses: actions/checkout@v2
-        with:
-          repository: kubernetes-sigs/cri-tools
-          path: src/sigs.k8s.io/cri-tools
-          ref: 5fd98895f3bbf8a3ba2d25e93fa95ba1e2ae0923
+      # - name: Check out cri-tools
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: kubernetes-sigs/cri-tools
+      #     path: src/sigs.k8s.io/cri-tools
+      #     ref: 5fd98895f3bbf8a3ba2d25e93fa95ba1e2ae0923
 
-      - name: Build cri-tools
-        working-directory: src/sigs.k8s.io/cri-tools
-        run: |
-          make critest crictl
-          find $(pwd)/build/bin -type f -exec mv {} /usr/local/bin \;
+      # - name: Build cri-tools
+      #   working-directory: src/sigs.k8s.io/cri-tools
+      #   run: |
+      #     make critest crictl
+      #     find $(pwd)/build/bin -type f -exec mv {} /usr/local/bin \;
 
-      - name: Checkout cri-dockerd
-        uses: actions/checkout@v2
-        with:
-          repository: ${{ github.repository }}
-          path: src/github.com/Mirantis/cri-dockerd
+      # - name: Checkout cri-dockerd
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: ${{ github.repository }}
+      #     path: src/github.com/Mirantis/cri-dockerd
 
-      - name: Build cri-dockerd
-        working-directory: src/github.com/Mirantis/cri-dockerd
-        run: |
-          go build
-          sudo mv ./cri-dockerd /usr/local/bin
+      # - name: Build cri-dockerd
+      #   working-directory: src/github.com/Mirantis/cri-dockerd
+      #   run: |
+      #     go build
+      #     sudo mv ./cri-dockerd /usr/local/bin
 
-      - name: Start cri-dockerd and run critest
-        working-directory: src/sigs.k8s.io/cri-tools
-        shell: bash
-        run: |
-          set -x
-          export LANG=C
-          export LC_ALL=C
+      # - name: Start cri-dockerd and run critest
+      #   working-directory: src/sigs.k8s.io/cri-tools
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     export LANG=C
+      #     export LC_ALL=C
 
-          # Install nsenter
-          docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
+      #     # Install nsenter
+      #     docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
 
-          # Start cri-dockerd first
-          logs_dir="${{ github.workspace }}/logs"
-          mkdir -p $logs_dir
-          sudo /usr/local/bin/cri-dockerd --log-level warn --network-plugin="" >$logs_dir/cri-dockerd.log 2>&1 &
+      #     # Start cri-dockerd first
+      #     logs_dir="${{ github.workspace }}/logs"
+      #     mkdir -p $logs_dir
+      #     sudo /usr/local/bin/cri-dockerd --log-level warn --network-plugin="" >$logs_dir/cri-dockerd.log 2>&1 &
 
-          # Wait a while for cri-dockerd starting.
-          sleep 10
+      #     # Wait a while for cri-dockerd starting.
+      #     sleep 10
 
-          # Run e2e test cases
-          # Skip reopen container log test because docker doesn't support it.
-          # Skip runtime should support execSync with timeout because docker doesn't
-          # support it.
-          # Skip apparmor test as we don't enable apparmor yet in this CI job, or selinux
-          sudo /usr/local/bin/critest -runtime-endpoint=unix:///var/run/cri-dockerd.sock -ginkgo.skip="runtime should support apparmor|runtime should support reopening container log|runtime should support execSync with timeout|runtime should support selinux|.*should support propagation.*"
+      #     # Run e2e test cases
+      #     # Skip reopen container log test because docker doesn't support it.
+      #     # Skip runtime should support execSync with timeout because docker doesn't
+      #     # support it.
+      #     # Skip apparmor test as we don't enable apparmor yet in this CI job, or selinux
+      #     sudo /usr/local/bin/critest -runtime-endpoint=unix:///var/run/cri-dockerd.sock -ginkgo.skip="runtime should support apparmor|runtime should support reopening container log|runtime should support execSync with timeout|runtime should support selinux|.*should support propagation.*"
 
-      - name: Run benchmark
-        working-directory: src/sigs.k8s.io/cri-tools
-        shell: bash
-        run: |
-          set -o errexit
-          set -o nounset
-          set -o pipefail
-          set -x
-          export LANG=C
-          export LC_ALL=C
+      # - name: Run benchmark
+      #   working-directory: src/sigs.k8s.io/cri-tools
+      #   shell: bash
+      #   run: |
+      #     set -o errexit
+      #     set -o nounset
+      #     set -o pipefail
+      #     set -x
+      #     export LANG=C
+      #     export LC_ALL=C
 
-          # Run benchmark test cases
-          sudo /usr/local/bin/critest -runtime-endpoint=unix:///var/run/cri-dockerd.sock -benchmark
+      #     # Run benchmark test cases
+      #     sudo /usr/local/bin/critest -runtime-endpoint=unix:///var/run/cri-dockerd.sock -benchmark
 
-      - name: Dump docker logs
-        if: always()
-        run: |
-          mkdir -p ${{ github.workspace }}/logs
-          sudo journalctl -eu docker | sudo tee ${{ github.workspace }}/logs/docker.log
-          ls -atrl ${{ github.workspace }}/logs
+      # - name: Dump docker logs
+      #   if: always()
+      #   run: |
+      #     mkdir -p ${{ github.workspace }}/logs
+      #     sudo journalctl -eu docker | sudo tee ${{ github.workspace }}/logs/docker.log
+      #     ls -atrl ${{ github.workspace }}/logs
 
-      - name: Upload logs
-        if: always()
-        uses: actions/upload-artifact@v1
-        with:
-          name: logs
-          path: logs
+      # - name: Upload logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v1
+      #   with:
+      #     name: logs
+      #     path: logs
